### ISSUE TITLE
Bug in ChamberAdjacencyGraph, "for a twisted polygonal complex"

### ISSUE THREAD

**Issue by aniemeyer** [gap-packages/simplicial-surfaces#199]
TwoAdjacencyClasses(complex) can return lists of length > 2 when there are several faces sharing one edge. When constructing the edges of the NautyEdgeColoredGraph all 2-subsets of this list need to be considere. Reymond has a minimal example which demonstrates the bug

**Comment by ReymondAkpanya** [comment]
The example is:
Given 
vof:=[[ 1, 5, 8 ], [ 1, 5, 6 ], [ 1, 6, 7 ], [ 1, 7, 8 ], [ 1, 3, 8 ] ];;
complex:=TriangularComplexByVerticesInFaces(vof);;

The  call "AutomorphismGroupOnVertices(complex);" returns an error.
