### ISSUE TITLE
Update list of package authors/maintainers/contributors?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/simplicial-surfaces#202]
Is @markusbaumeister really still maintainer of the package? If not, perhaps consider setting is maintainer flag to `false`?

Likewise: Is @aniemeyer still maintainer? As in: going to take care of addressing bugs, merging PRs, making releases...?

Is anyone else effectively maintainer? If so, it'd be great to have them in the `PackageInfo.g` so that we (the GAP team) know whom to contact if there is urgent need for a fix in this package (of course this only would become relevant if this package were to be deposited into the GAP package distribution, it currently isn't).

Related to that, you can also add the GAP Team as co-maintainer (as some packages have), that would mean we'd take care of trivial routine fixes and possibly releases if desired/necessary. But this is purely optional and your choice.

**Comment by aniemeyer** [comment]
Markus Baumeister is not working as a package maintainer any longer. The current current maintainers will be added to the package. The GAP Team will be added as co-maintainer.
